package VotingPoll::Model::VotingPollDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'VotingPoll::Schema::VotingPollDB',
    
    connect_info    => {
        dsn         => 'dbi:mysql:voting_poll',
        user        => 'voting_poll',
        password    => 'StRaW101',
    }
);

=head1 NAME

VotingPoll::Model::VotingPollDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<VotingPoll>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<VotingPoll::Schema::VotingPollDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
